server:
  port: 8081
spring:
  application:
    name: auth-center
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///auth
  main:
    allow-bean-definition-overriding: true # 允许Spring默认bean
logging:
  level:
    spring: debug
    dev.kun: debug
    org:
      apache:
        ibatis: debug
